[package]
name = "loading-music"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11.6"
songbird = "0.3.2"
tokio = {version = "1.32.0", features = ["rt-multi-thread"]}
